<a href="https://colab.research.google.com/github/tagtag/TD_based_FE/blob/master/Sec_4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
install.packages("diptest")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



Teble 4.9 (N,M) =(1000,20),(1000,10),(100,20),(100,10)

In [3]:
N<-1000
M<-10
N1<-10
require(MASS)
require(diptest)
t0<-NULL
lm0<-NULL
pca0<-NULL
var0<-NULL
dip0<-NULL
for (i in c(1:100))
{
cat(i, " ")
x <- matrix(NA,N,M)
x[1:N,1:(M/2)] <- rnorm(N*(M/2))
x[1:N,(M/2+1):M] <- rnorm(N*(M/2),4)
x[(N1+1):N,]<- apply(x[(N1+1):N,],1,sample) 
Pt <- apply(x,1,function(x){t.test(x[1:(M/2)],x[(M/2+1):M])$p.value})
t_l <- c(1:N)[p.adjust(Pt,"BH")<0.01]
t0<- cbind(t0,c(sum(1:N1 %in% t_l),sum(!(1:N1 %in% t_l)),sum(!(t_l %in% 1:N1))))
pca <- prcomp(x)
PP <- pchisq(scale(pca$x[,1])^2,1,lower.tail=F)
pca_l <- c(1:N)[p.adjust(PP,"BH")<0.01]
pca0<- cbind(pca0,c(sum(1:N1 %in% pca_l),sum(!(1:N1 %in% pca_l)),sum(!(pca_l %in% 1:N1))))
Pd <- apply(x,1,function(x){dip.test(x)$p.value})
dip_l <- c(1:N)[p.adjust(Pd,"BH")<0.01]
dip0<- cbind(dip0,c(sum(1:N1 %in% dip_l),sum(!(1:N1 %in% dip_l)),sum(!(dip_l %in% 1:N1))))
}

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100  

t test

In [6]:
matrix(c(rowMeans(t0),N-sum(rowMeans(t0))),2,2)

[,1] [,2]  
[1,] 1.05   0.18
[2,] 8.95 989.82

pca

In [7]:
matrix(c(rowMeans(pca0),N-sum(rowMeans(pca0))),2,2)

[,1] [,2]
[1,]  0     0 
[2,] 10   990

uninodal test

In [8]:
matrix(c(rowMeans(dip0),N-sum(rowMeans(dip0))),2,2)

[,1] [,2]  
[1,]  0     0.01
[2,] 10   989.99

Table 4.10

In [9]:
N<-1000
M<-10
N1<-10
require(MASS)
require(diptest)
t0<-NULL
lm0<-NULL
pca0<-NULL
var0<-NULL
dip0<-NULL
for (i in c(1:100))
{
cat(i, " ")
x <- matrix(NA,N,M)
x[1:N,1:(M/2)] <- rnorm(N*(M/2))
x[1:N,(M/2+1):M] <- rnorm(N*(M/2),4)
x[(N1+1):N,] <- rnorm((N-N1)*M,2) #2
Pt <- apply(x,1,function(x){t.test(x[1:(M/2)],x[(M/2+1):M])$p.value})
t_l <- c(1:N)[p.adjust(Pt,"BH")<0.01]
t0<- cbind(t0,c(sum(1:N1 %in% t_l),sum(!(1:N1 %in% t_l)),sum(!(t_l %in% 1:N1))))
pca <- prcomp(x)
PP <- pchisq(scale(pca$x[,1])^2,1,lower.tail=F)
pca_l <- c(1:N)[p.adjust(PP,"BH")<0.01]
pca0<- cbind(pca0,c(sum(1:N1 %in% pca_l),sum(!(1:N1 %in% pca_l)),sum(!(pca_l %in% 1:N1))))
Pd <- apply(x,1,function(x){dip.test(x)$p.value})
dip_l <- c(1:N)[p.adjust(Pd,"BH")<0.01]
dip0<- cbind(dip0,c(sum(1:N1 %in% dip_l),sum(!(1:N1 %in% dip_l)),sum(!(dip_l %in% 1:N1))))
}

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99  100  

t.test

In [10]:
matrix(c(rowMeans(t0),N-sum(rowMeans(t0))),2,2)

[,1] [,2]  
[1,] 0.92   0.01
[2,] 9.08 989.99

pca

In [11]:
matrix(c(rowMeans(pca0),N-sum(rowMeans(pca0))),2,2)

[,1] [,2]
[1,] 9.32   0 
[2,] 0.68 990

Unimodal test

In [12]:
matrix(c(rowMeans(dip0),N-sum(rowMeans(dip0))),2,2)

[,1] [,2]
[1,]  0     0 
[2,] 10   990